### ISSUE TITLE
Dependencies are not installed

### ISSUE THREAD

**Issue by maxpowersi** [adde88/hostapd-mana-openwrt#6]
Debuguing the dependencies.sh i think the wgets are wrong, because that URL is 404 not found on github.

Regards, and good job!

**Comment by maxpowersi** [comment]
error.

**Comment by adde88** [comment]
You're reporting an error for the module, correct?

**Comment by maxpowersi** [comment]
No sorry, this is my bad, i wanted to report this "Mana Toolkit", considered this issue an error. Many thanks!

**Comment by adde88** [comment]
I've fixed the dependencies.sh script now on Mana Toolkit
It should correctly locate the IPK files.
