### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by b0n3zx** [adde88/hostapd-mana-openwrt#9]
Copied the wget and this is what happened.  Pineapple Tetra FW 2.7.0 

root@Pineapple:~# wget -qO- https://raw.githubusercontent.com/adde88/hostapd-mana/master/INSTALL.sh | bash -s -- -v -v
Installing: hostapd-mana.
Go grab a cup of coffee, this will take a while...

Downloading https://downloads.hak5.org/packages/mk6/190702/Packages.gz
Updated list of available packages in /var/opkg-lists/190702_pineapple
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/1907_base
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/1907_packages
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/1907_routing
Unknown package 'hostapd-mana'.
Installing sslsplit (0.5.5) to root...
Downloading https://downloads.hak5.org/packages/mk6/190702/sslsplit_0.5.5_mips_24kc.ipk
Installing musl-fts (1.2.7-1) to root...
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/packages/musl-fts_1.2.7-1_mips_24kc.ipk
Configuring musl-fts.
Configuring sslsplit.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for hostapd-mana found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package hostapd-mana.
bash: line 37: /etc/init.d/stunnel: No such file or directory
Installation completed!
Type: 'install-mana-depends' to install python-related dependencies.
Launch hostapd-mana by typing: 'launch-mana' in the terminal.

WARNING: This script has not been updated for the Pineapple MK7 yet! And will most likely fail on this device!
uci: Entry not found
uci: Entry not found
root@Pineapple:~#

**Comment by adde88** [comment]
What device are you trying to install it on?

**Comment by forensictdev** [comment]
Same error, I am trying to install it on Pineapple Nano with firmware updated to 2.7.0

root@Pineapple:/sd/test# cat /proc/cpuinfo 
system type		: Atheros AR9330 rev 1
machine			: Hak5 WiFi Pineapple NANO
processor		: 0
cpu model		: MIPS 24Kc V7.4
BogoMIPS		: 265.42
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 16
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16
Options implemented	: tlb 4kex 4k_cache prefetch mcheck ejtag llsc dc_aliases perf_cntr_intr_bit nan_legacy nan_2008 perf
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

**Comment by adde88** [comment]
Please show me the process you're using to install it.
Like, the exact URL of the file/IPK you're trying to install.

It makes it alot easier for me to provide support if you're giving me some more info on what you're doing.

Please remember that the Pineapple TETRA & NANO (MK6) with the latest firmware should be using files from the _packages_19.07_mkvi_ branch:
https://github.com/adde88/openwrt-useful-tools/tree/packages-19.07_mkvi

The files on the "master" branch (_packages_19.07_mkvii_) are ONLY for the Pineapple MK7, and WILL fail if someone is trying to install them on the TETRA/NANO.

**Comment by forensictdev** [comment]
Thank you for your early response.

I am using the script INSTALL.sh from here: https://github.com/adde88/hostapd-mana/blob/openwrt-19.07/INSTALL.sh

root@Pineapple:/sd# wget -qO- https://raw.githubusercontent.com/adde88/hostapd-mana/master/INSTALL.sh | bash -s -- -v -v
Installing: hostapd-mana.
Go grab a cup of coffee, this will take a while...

Downloading https://downloads.hak5.org/packages/mk6/190702/Packages.gz
Updated list of available packages in /var/opkg-lists/190702_pineapple
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/1907_base
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/1907_packages
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/1907_routing
Unknown package 'hostapd-mana'.
Installing sslsplit (0.5.5) to sd...
Downloading https://downloads.hak5.org/packages/mk6/190702/sslsplit_0.5.5_mips_24kc.ipk
Installing musl-fts (1.2.7-1) to sd...
Downloading https://downloads.openwrt.org/releases/packages-19.07/mips_24kc/packages/musl-fts_1.2.7-1_mips_24kc.ipk
Configuring musl-fts.
Configuring sslsplit.
Collected errors:
  pkg_hash_fetch_best_installation_candidate: Packages for hostapd-mana found, but incompatible with the architectures configured
  opkg_install_cmd: Cannot install package hostapd-mana.
  extract_archive: Cannot create symlink from ./usr/lib/libfts.so to 'libfts.so.0.0.0': Operation not permitted.
  extract_archive: Cannot create symlink from ./usr/lib/libfts.so.0 to 'libfts.so.0.0.0': Operation not permitted.
bash: /etc/init.d/stunnel: not found
Installation completed!
Type: 'install-mana-depends' to install python-related dependencies.
Launch hostapd-mana by typing: 'launch-mana' in the terminal.

WARNING: This script has not been updated for the Pineapple MK7 yet! And will most likely fail on this device!
uci: Entry not found
uci: Entry not found

Reading the script I see that download the ipk files from here: https://github.com/adde88/hostapd-mana-openwrt/raw/openwrt-19.07/bin/packages/mipsel_24kc/custom/

I have installed manually from the repo that you indicated above, but other error appears for both MK6 and MK7

root@Pineapple:/sd/test/version# wget https://github.com/adde88/openwrt-useful-tools/blob/packages-19.07_mkvi/hostapd-mana_2.6.5-27_mips_24kc.ipk
root@Pineapple:/sd/test/version# opkg --dest sd --force-overwrite install hostapd-mana_2.6.5-27_mips_24kc.ipk 
Collected errors:
  pkg_init_from_file: Malformed package file hostapd-mana_2.6.5-27_mips_24kc.ipk.
root@Pineapple:/sd/test/version7# wget https://github.com/adde88/openwrt-useful-tools/blob/packages-19.07_mkvii/hostapd-mana_2.6.5-27_mipsel_24kc.ipk
root@Pineapple:/sd/test/version7# opkg --dest sd --force-overwrite install hostapd-mana_2.6.5-27_mipsel_24kc.ipk 
Collected errors:
  pkg_init_from_file: Malformed package file hostapd-mana_2.6.5-27_mipsel_24kc.ipk.

**Comment by adde88** [comment]
Please provide as much information as possible when submitting issues. It really helps tracking down the root of the issue!
For example, what device are you using? What firmware version are you running?
And please DOUBLE check that your Pineapple is ONLINE, capable of downloading files, etc.
Output from both **dmesg** and **logread** AFTER experiencing the issue is VERY useful!
Please use [pastebin](https://pastebin.com/) to upload these logs. DO NOT paste the logs here!
Issues not following these instructions will get closed.

At the time of submission the INSTALLER script was not updated for the MK7 (which it states in the output.)
The script has been updated, and should now detect what device you are using and then download the correct packages.
I recommend testing the latest script, and making sure to follow the above instructions if you still experience problems.
It also looks like you are experiencing problems with your SD-card on your NANO. Which is a very common problem on the NANO.
I assume this as the script fails to sym-link the **musl-fts** library properly. (Output from **dmesg** and **logread** after experiencing this problem will tell clearly what's going on.)
The "SD-card bug" will also cause ALOT of other problems when using my packages and scripts.
